language: swift
osx_image: xcode12.0
branches:
  only:
  - master

before_install:
 - gem install fastlane --no-ri --no-rdoc --nodocument
install: true
script:
 - fastlane scan --scheme TAU --device "iPhone 11 Pro Max"
